ARG BUILD_FROM="python:3.10.1-slim"
FROM $BUILD_FROM

ENV WORK_DIR=/app
WORKDIR $WORK_DIR

RUN pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir streamlit

COPY ./frontend/app/ .

EXPOSE 8501

CMD ["bash", "./run-app.sh"]
