ARG BUILD_FROM="entelecheia/ekorpkit:latest-pytorch1.11-runtime"
FROM $BUILD_FROM

# Set up environment variables
ENV WORK_DIR=/app
ENV EKORPKIT_CONFIG_DIR=$WORK_DIR/config
ENV EKORPKIT_PROJECT=ekorpkit-app

WORKDIR $WORK_DIR

COPY ./backend/app .

EXPOSE 8080

CMD ["bash", "./run-app.sh"]
