ARG BUILD_FROM="ekorpkit:nightly-nvidia-pytorch22.02-runtime"
FROM $BUILD_FROM

RUN pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir fastapi uvicorn
RUN pip install --no-cache-dir -U --pre ekorpkit[art]

# Set up environment variables
ENV WORK_DIR="/app"
ENV EKORPKIT_CONFIG_DIR="$WORK_DIR/config"
ENV EKORPKIT_PROJECT="ekorpkit-app"

WORKDIR $WORK_DIR

COPY ./backend/app .

EXPOSE 8080

CMD ["bash", "./run-app.sh"]
